targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          disallow_unrecognized_keys: true
          explicit_to_json: true
      drift_dev:
        options:
          databases:
            # Required: A name for the database and its path
            my_database: lib/db/app_database.dart
          store_date_time_values_as_text: true