name: sbb
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  json_annotation: ^4.9.0
  collection: any
  geolocator: ^14.0.2
  flutter_map: ^8.1.1
  flutter_map_animations: ^0.9.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  go_router: ^16.0.0
  flutter_staggered_grid_view: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.5.4
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
